packages:
  - .templates/*
  - packages/*

catalog:
  '@biomejs/biome': ^1.9.4
  '@storybook/addon-essentials': ^8.4.5
  '@storybook/addon-interactions': ^8.4.5
  '@storybook/addon-links': ^8.4.5
  '@storybook/blocks': ^8.4.5
  '@storybook/react': ^8.4.5
  '@storybook/react-vite': ^8.4.5
  '@storybook/test': ^8.4.5
  happy-dom: ^15.7.4
  knip: ^5.34.1
  storybook: ^8.4.5
  tsup: ^8.3.5
  typescript: ^5.6.3
  vitest: ^2.1.4
