name: CI

on:
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - name: pnpm 설치
      uses: pnpm/action-setup@v4
      with:
        run_install: false
    - name: Node.js 환경 설정
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version-file: .nvmrc
    - name: 의존성 설치
      run: pnpm install
    - name: 린트
      run: pnpm --filter="...[origin/${{ github.base_ref }}]" "/lint:*/"
    - name: 테스트
      run: pnpm --filter="...[origin/${{ github.base_ref }}]" test
    - name: 타입 체크
      run: pnpm --filter="...[origin/${{ github.base_ref }}]" typecheck
    - name: 빌드
      run: pnpm --filter="...[origin/${{ github.base_ref }}]" build
