name: CI

on:
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: pnpm 설치
      uses: pnpm/action-setup@v4
      with:
        run_install: false
    - name: Node.js 환경 설정
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version-file: .nvmrc
    - name: 의존성 설치
      run: pnpm install
    - name: 린트
      run: pnpm --filter=[origin/main] lint
    - name: 테스트
      run: pnpm --filter=[origin/main] test
    - name: 빌드
      run: pnpm --filter=[origin/main] build
    - name: 타입 체크
      run: pnpm --filter=[origin/main] typecheck
